extends Node

# VECTOR UTILITY CONSTANTS
const UPLEFT = Vector2(-1, 1)
const UPRIGHT = Vector2(1, 1)
const DOWNLEFT = Vector2(-1, -1)
const DOWNRIGHT = Vector2(1, -1)

# BASE ENTITY SPEED
const ENTITY_BASE_SPEED = 200

# PROJECTILES
const PROJECTILE_MAX_DISTANCE = 4000